apiVersion: apps/v1
kind: Deployment
metadata:
  name: nana-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nana-backend
  template:
    metadata:
      labels:
        app: nana-backend
    spec:
      containers:
        - name: backend
          image: nana-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DB_HOST
              value: nana-postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: "12345678"
            - name: DB_NAME
              value: comerciante_nana
            - name: TYPEORM_SYNCHRONIZE
              value: "true"
            - name: JWT_SECRET
              value: cambia_este_secreto_en_produccion
            - name: ADMIN_EMAIL
              value: admin@nana.com
            - name: ADMIN_PASSWORD
              value: Admin123!
            - name: RECAPTCHA_SECRET
              value: clave_recaptcha_dev
---
apiVersion: v1
kind: Service
metadata:
  name: nana-backend
spec:
  type: NodePort
  selector:
    app: nana-backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
