import type { JuegoDeMesa, Sucursal } from './tipos_de_datos';

export const lista_de_juegos: JuegoDeMesa[] = [
  {
    id: 'juego_1',
    nombre: 'Tulio Lulo Lana Tarro Patana',
    categoria: 'Party Games',
    precio: 60,
    jugadores: '2 - 8',
    tiempo: '15 min',
    edad: '8+',
    imagen: '/imagenes/Tulio31Minutos.png',
    descripcion: 'Un juego de cartas rápido basado en 31 Minutos. ¡Diversión garantizada!',
    en_stock: true,
  },
  {
    id: 'juego_2',
    nombre: 'Pop Up Pirate',
    categoria: 'Familiares',
    precio: 30,
    jugadores: '2 - 4',
    tiempo: '10 min',
    edad: '3+',
    imagen: '/imagenes/PopUpPirate.png',
    descripcion: 'El clásico juego de suspenso del barril.',
    en_stock: true,
  },
  {
    id: 'juego_3',
    nombre: 'Secret Hitler',
    categoria: 'Estrategia',
    precio: 150,
    jugadores: '5 - 10',
    tiempo: '45 min',
    edad: '13+',
    imagen: '/imagenes/SecretHitler.png',
    descripcion: 'Intriga política y traición en los años 30.',
    en_stock: true,
  },
  {
    id: 'juego_4',
    nombre: 'Dobble',
    categoria: 'Party Games',
    precio: 85,
    jugadores: '2 - 8',
    tiempo: '15 min',
    edad: '6+',
    imagen: '/imagenes/Dobble.png',
    descripcion: 'Encuentra el símbolo idéntico antes que nadie.',
    en_stock: true,
  },
  {
    id: 'juego_5',
    nombre: 'Mal Trago',
    categoria: 'Party Games',
    precio: 120,
    jugadores: '4 - 10',
    tiempo: '20 min',
    edad: '8+',
    imagen: '/imagenes/MalTrago.png',
    descripcion: 'Pociones, risas y muchas despedidas.',
    en_stock: true,
  },
  {
    id: 'juego_6',
    nombre: 'Saboteur',
    categoria: 'Estrategia',
    precio: 95,
    jugadores: '3 - 10',
    tiempo: '30 min',
    edad: '8+',
    imagen: '/imagenes/Saboteur.png',
    descripcion: 'Enanos mineros contra saboteadores.',
    en_stock: true,
  },
  {
    id: 'juego_7',
    nombre: 'Monopoly',
    categoria: 'Familiares',
    precio: 180,
    jugadores: '2 - 6',
    tiempo: '90 min',
    edad: '8+',
    imagen: '/imagenes/Monopoly.png',
    descripcion: 'El gran juego de las propiedades.',
    en_stock: true,
  },
  {
    id: 'juego_8',
    nombre: 'UNO',
    categoria: 'Cartas',
    precio: 45,
    jugadores: '2 - 10',
    tiempo: '20 min',
    edad: '7+',
    imagen: '/imagenes/UNO.png',
    descripcion: 'No olvides gritar ¡UNO!',
    en_stock: true,
  },
  {
    id: 'juego_9',
    nombre: 'DOS',
    categoria: 'Cartas',
    precio: 50,
    jugadores: '2 - 4',
    tiempo: '20 min',
    edad: '7+',
    imagen: '/imagenes/DOS.png',
    descripcion: 'Porque uno no era suficiente.',
    en_stock: true,
  },
  {
    id: 'juego_10',
    nombre: 'Exploding Kittens',
    categoria: 'Cartas',
    precio: 110,
    jugadores: '2 - 5',
    tiempo: '15 min',
    edad: '7+',
    imagen: '/imagenes/ExplodingKittens.png',
    descripcion: 'Gatitos explosivos y mucha mala leche.',
    en_stock: true,
  }
];

export const sucursales: Sucursal[] = [
  { id: '1', ciudad: 'La Paz - Prado', direccion: 'Calle Campero #48, Piso 2', referencia: 'Frente al Obelisco' },
  { id: '2', ciudad: 'El Alto', direccion: 'C. Jorge Carrasco, Galería Flor de Oro', referencia: 'Of. 1' },
  { id: '3', ciudad: 'Cochabamba', direccion: 'C. Nataniel Aguirre, Galería Colonial', referencia: 'L8' }
];